#!/bin/bash
#
# Backup the m1330

sources=("/home/henrik/projects" "/home/henrik/.mail" "/home/henrik/documents" "/home/henrik/ebooks")
backup_root="/home/backup/m1330"

source_dir="/tmp/backup.$$"

function _cleanup {
    rm -rf $source_dir
}

function _fatal {
    echo "Fatal: $*" >&2
    _cleanup
    exit 1
}


# Symlink all sources to the backup directory
mkdir -p "$source_dir" || _fatal "Failed to create $source_dir"
for s in ${sources[@]}; do
    ln -s "$s" "$source_dir/${s##*/}" || _fatal "Failed to link $s"
done

# Backup
backup -s "$source_dir" -d "$backup_root" -v || _fatal "Failed to backup"

# And clean up
_cleanup
