#!/bin/bash
# 
# Backup the Windows desktop

source_folders=(Henrik Karin Musik Pictures Videos)
backup_root="/home/backup/desktop"

desktop_ip=$(gethostip -d desktop)
mountpoint=$(mktemp -d)

function cleanup {
    for f in "$mountpoint/*"; do
        umount $f >/dev/null 2>&1
        rmdir $f >/dev/null 2>&1
    done
    rmdir $mountpoint >/dev/null 2>&1
}

function _fatal {
    echo "Fatal: $*" >&2
    exit 1
}


# Must be root
[[ $(id -u) -eq 0 ]] || _fatal "Must be root"

# Make sure we can talk to desktop
ping -q -c 1 $desktop_ip > /dev/null 2>&1 || _fatal "Desktop not reachable"

trap cleanup INT TERM EXIT

# Mount all folders
mkdir -p $mountpoint || _fatal "Could not create mountpoint $mountpoint"
for dir in "${source_folders[@]}"; do
    mkdir -p "$mountpoint/$dir" || _fatal "Could not create mountpoint $mountpoint"
    mount.cifs "//$desktop_ip/$dir" "$mountpoint/$dir" -o iocharset=utf8,password="" || _fatal "Could not mount $dir" 
done

# Backup
backup -s "$mountpoint" -d "$backup_root" -v || _fatal "Backup failed"

# Give all read access
chmod -R a+r "$backup_root" || _fatal "Failed to chmod backup"
find "$backup_root" -type d -exec chmod 755 {} \;
