#!/bin/sh
#
# Select columns out of PS CSV files into comma separated file
# Eg bzcat 20130813_name.csv.bz2 | pscsvcut wager,win | head

tr -d "\r" | sed '1,2d;3s|^# *||;s|;|,|g' | awk -F, -v cols="${1:?}" '
   BEGIN {
     n=split(cols,col)
     for (i=1; i<=n; i++) {
         s[col[i]]=i
     }
   }
   NR==1 {
     for (f=1; f<=NF; f++)
       if ($f in s) {
           c[s[$f]]=f
       }
     next
   }
   { sep=""
     for (f=1; f<=n; f++) {
       printf("%c%s",sep,$c[f])
       sep=FS
     }
     print ""
   }
'
