#!/usr/bin/lua
-- Update statusline for dwm and dvtm.
-- No looping, keepalive etc since my dwm updates clocks etc internally
-- See http://github.com/halhen/dwm-halhen

function mocp()
    m = io.popen("/usr/bin/mocp -i 2>/dev/null")
    local state = m:read() or ""
    local file = m:read() or ""
    local title = m:read() or ""
    local artist = m:read() or ""
    local songtitle = m:read() or ""

    file = file:sub(7)
    title = title:sub(8)
    artist = artist:sub(9)
    songtitle = songtitle:sub(12)

    if artist ~= "" and title ~= "" then return artist .. " - " .. title end
    if songtitle ~= "" then return songtitle end
    if title ~= "" then return title end
    if artist ~= "" then return artist end
    if file ~= "" then 
        file, _ = file:gsub("(.*/)(.*)", "%2")
        return file 
    end
end

function setstatus(s)
    -- Set dwm status text
    if xsetroot then
        os.execute('xsetroot -name "' .. s .. '" 2>/dev/null')
    else
        io.write(s .. "\n")
        io.flush()
    end
end

-- Read command line
xsetroot=true
for posn, val in ipairs(arg) do
    if val == "-s" then
        xsetroot=false
    else
        error("Bad argument.\nValid options are:\n   -s: write to stdout")
    end
end

all = {mocp()}

data = {}
for k, v in pairs(all) do
        table.insert(data, v)
end

s = table.concat(data, ' | ')
setstatus(s)
