#!/bin/bash
#
# Simple but sufficiently good way to sync the computers clock

# Verify root
[[ $UID -ne 0 ]] && { echo "Error: must be root" >&2; exit 1; }

# Retrieve time
now=$(awk '{if (NF>1) print $2,$3 " UTC"}' < /dev/tcp/time.nist.gov/13)
[[ "x$now" == "x" ]] && { echo "Error: failed to retrieve time" >&2; exit 2; }

# Set time
hwclock --set --date="$now"
hwclock -s
