#!/bin/bash

TIXIDIR="$HOME/.tixi"
TIXISYNC=true

cd "$TIXIDIR"

TIXIHELP="Usage: $(basename $0) [-h] [-s] [-S] [-a file text] [-i text] [-r file] [-e]

Options
    -h            Print this help and exit

  Synchronization
    -s            Syncronize tixi to the central repo (default)
    -S            Don't syncronize tixi

  Modification
    -a file text  Append \$text to \$file
    -i text       Timestamp and append \$text to the inbox

  Extraction
    -r file       Print contents of \$file

  Interactive
    -e            Open editor with default files open

Examples
    Sync only

        $ tixi

    Batch insert into Inbox, then sync

        $ tixi -S -i First entry
        $ tixi -S -i Second entry
        $ tixi"

while getopts "hsSia:ir:e" flag; do
    case $flag in
        h) echo "$TIXIHELP"; exit 1;;

        s) TIXISYNC=true;;
        S) TIXISYNC=false;;

        a) TIXI_DOAPPENDTO="$OPTARG";;
        i) TIXI_DOINBOX=true;;

        r) TIXI_DOREAD="$OPTARG";;

        e) TIXI_DOOPEN=true;;
    esac
done
shift $((OPTIND-1))

$TIXISYNC && ./.meta/sync-down

# Perform
if [ "$TIXI_DOINBOX" ]; then
    echo "$(date +"%Y-%m-%d %H:%M"): $@" >> "todo" || exit 1
fi

if [ "$TIXI_DOAPPENDTO" ]; then
    echo "$@" >> "$TIXI_DOAPPENDTO" || exit 1
fi

if [ "$TIXI_DOOPEN" ]; then
    vim -p diary/$(date "+%Y-%m-%d") todo
fi

if [ "$TIXI_DOREAD" ]; then
    cat "$TIXI_DOREAD" || exit 1
fi


$TIXISYNC && ./.meta/sync-up

exit 0
