#!/bin/bash
#
# Compose and set a wallpaper from disc, URL or from top images on reddit.com.
# Edit the last line for a command that sets the wall in your window manager 
#
# Usage:
#  Use a local file.
#    $ wallpaper /some/local/picture.jpg
#
#  Fetch and use a file from an URL.
#    $ wallpaper http://www.somesite.com/with/image.png
#
#  Fetch a random current top image from reddit (not marked NSFW). 
#  Edit $REDDITSUBS below to set which subreddits to check for images.
#    $ wallpaper
#
# Adapted from http://redd.it/kp7kr


# Which subreddits should we check for images?
REDDITSUBS="earthporn+villageporn+itookapicture+specart+ImaginaryLandscapes+SpacePorn"
# How big should the foreground image be on the wallpaper?
IMAGESIZE="(6/10)"


SOURCE="$1"
if [ "x$SOURCE" == "x" ]; then 
    # If no $SOURCE is specified, fetch a random current top image from reddit
    SOURCE=$(wget -q http://www.reddit.com/r/$REDDITSUBS/.rss -O- | \
             sed 's/<item>/\n&/g' | \
             grep -iv NSFW | \
             egrep -oi '[a-z]+://[^; ]*.(jpg|jpeg|png)' | \
             grep -v 'thumbs.reddit.com' | \
             shuf -n1)
fi

IMAGE=$(basename "$SOURCE")

DIR=$(mktemp -d)
cd "$DIR" || exit 1
trap 'rm -rf $DIR' EXIT

if [ $(echo "$SOURCE" | grep '^[a-z]\+://') ]; then
    wget -q "$SOURCE" -O "$IMAGE" || exit 1
else
    cp "$SOURCE" "$IMAGE" || exit 1
fi

BG="${IMAGE//.*}_bg.${IMAGE##*.}"
DEST="output.${IMAGE##*.}"

RESOLUTION=$(xrandr 2>/dev/null | \
                sed -n "s|.*current \([0-9]*\) x \([0-9]*\).*|\1x\2|p")
BGZOOM=$(echo "$RESOLUTION" | awk -Fx '{print $1*2 "x" $2*2}')
BGOFFSET=$(echo "$RESOLUTION" | awk -Fx '{print "+" $1/3 "+" $2/3}')
IMAGERES=$(echo "$RESOLUTION" | \
               awk -Fx '{print $1*'$IMAGESIZE' "x" $2*'$IMAGESIZE'}')

cp "$IMAGE" "$BG" || exit 1

mogrify \( -modulate 25,0,100 \) \
        \( -resize $BGZOOM^  \) \
        \( -crop "$RESOLUTION""$BGOFFSET" \) \
        \( -blur 128 \) -quality 96 "$BG"

mogrify \( -resize ${IMAGERES} \) \
        \( -bordercolor white -border 10 \) "$IMAGE"

composite -gravity center "$IMAGE" "$BG" "$DEST"

feh --bg-center "$DEST"
