#!/bin/bash
#
# Compose and set a wallpaper from disc, URL or from top images on reddit.com.
# Edit the last line for a command that sets the wall in your window manager 
#
# Usage:
#  Use a local file.
#    $ wallpaper /some/local/picture.jpg
#
#  Fetch and use a file from an URL.
#    $ wallpaper http://www.somesite.com/with/image.png
#
#  Fetch a random current top image from reddit (not marked NSFW). 
#  Edit $REDDITSUBS below to set which subreddits to check for images.
#    $ wallpaper
#
# Adapted from http://redd.it/kp7kr

function die {
    echo "Fatal: $@" >&2
    exit 1
}


# Which subreddits should we check for images?
REDDITSUBS="specart+ImaginaryLandscapes+SpacePorn"
# How big part of the screen should the foreground image be?
IMAGESIZE="(6/10)"


SOURCE="$1"
if [ "x$SOURCE" == "x" ]; then 
    # If no $SOURCE is specified, fetch a random current top image from reddit
    SOURCE=$(wget -q http://www.reddit.com/r/$REDDITSUBS/.rss -O- | \
             sed 's/<item>/\n&/g' | \
             grep -iv NSFW | \
             grep -Eoi '[a-z]+://[^<; ]*.(jpg|jpeg|png)' | \
             grep -v 'reddit.com' | \
             grep -v 'redditmedia.com' | \
             shuf -n1)
fi

IMAGE=$(basename "$SOURCE")

DIR=$(mktemp -d)
cd "$DIR" || die "Failed to enter working directory $DIR"
trap 'rm -rf $DIR' EXIT

if [ $(echo "$SOURCE" | grep '^[a-z]\+://') ]; then
    wget -q "$SOURCE" -O "$IMAGE" || die "Failed to download $SOURCE to $IMAGE"
else
    cp "$SOURCE" "$IMAGE" || die "Failed fo copy $SOURCE to $IMAGE"
fi

DEST="output.${IMAGE##*.}"

RESOLUTION=$(xrandr 2>/dev/null | \
                sed -n "s|.*current \([0-9]*\) x \([0-9]*\).*|\1x\2|p")
BGZOOM=$(echo "$RESOLUTION" | awk -Fx '{print $1*2 "x" $2*2}')
BGOFFSET=$(echo "$RESOLUTION" | awk -Fx '{print "+" $1/3 "+" $2/3}')

cp "$IMAGE" "$DEST" || die "Failed to copy $IMAGE to $DEST"

mogrify \( -modulate 25,0,100 \) \
        \( -resize $BGZOOM^  \) \
        \( -crop "$RESOLUTION""$BGOFFSET" \) \
        \( -blur 128 \) -quality 96 "$DEST"

xrandr 2>/dev/null | sed -n 's|.* connected \([^ ]*\).*|\1|p' | while read MONITORGEOM; do
    IMAGERES=$(echo "$MONITORGEOM" | \
               tr '+' 'x' | \
               awk -Fx '{W=$1*'$IMAGESIZE';
                         H=$2*'$IMAGESIZE';
                         printf "%.0fx%.0f",W,H;}')

    mogrify \( -resize ${IMAGERES} \) \
            \( -bordercolor white -border 10 \) "$IMAGE"

    NEWSIZE=$(identify "$IMAGE" | awk '{print $3}')
    IMAGEGEOM=$(echo "${MONITORGEOM}x${NEWSIZE}" | \
                tr '+' 'x' | \
                awk -Fx '{X=$3+($1-$5)/2;
                          Y=$4+($2-$6)/2;
                          printf "+%0.f+%0.f",X,Y;}')

    composite -geometry "$IMAGEGEOM" "$IMAGE" "$DEST" "$DEST"
done

feh --bg-center "$DEST"
