#!/bin/bash

v4l2-ctl --set-ctrl brightness=136
v4l2-ctl --set-ctrl contrast=132
v4l2-ctl --set-ctrl saturation=135
v4l2-ctl --set-ctrl sharpness=194
v4l2-ctl --set-ctrl zoom_absolute=128
v4l2-ctl --set-ctrl pan_absolute=14400

