#!/bin/bash
#
# pbrisbin 2010
# Adapted from http://pbrisbin.com/bin/xdg-open 
#
# put this at /usr/bin/xdg-open (or just ahead of it in $PATH) and
# chromium will open apps sanely without all that .desktop crap
#
###

file="$1"

if [[ ! -f "$file" ]]; then
  exec /usr/bin/xdg-open "$file"
fi

# read the major and minor mimetype
IFS='/' read -r major minor < <(file -ib "$file" 2>/dev/null | cut -d ';' -f 1)

# check for a specific case
case "$major/$minor" in
  text/html)       $BROWSER "$file" &>/dev/null & exit 0 ;;
  application/pdf) zathura "$file"  &>/dev/null & exit 0 ;;
esac

# check for just a major match
case "$major" in
  image) mirage "$file"        &>/dev/null & exit 0 ;;
  text)  urxvtc -e vim "$file" &>/dev/null & exit 0 ;;
  video) vlc "$file"           &>/dev/null & exit 0 ;;
esac

exec /usr/bin/xdg-open "$file"
